
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest_command:
  power_on:
    url: "http://192.168.178.230/toggle?state=on"
    method: post
  power_off:
    url: "http://192.168.178.230/toggle?state=off"
    method: post

binary_sensor:
  - platform: tod
    name: Dusk
    after: sunset
    after_offset: "-00:30"
    before: sunset
    before_offset: "1:30"
    unique_id: dusk_sensor
  - platform: rest
    name: LampState
    resource: http://192.168.178.230/state
